<?php

namespace UtilisateursBundle\Repository;

/**
 * classeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class classeRepository extends \Doctrine\ORM\EntityRepository
{
}
