<?php

namespace UtilisateursBundle\Repository;

/**
 * postRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class postRepository extends \Doctrine\ORM\EntityRepository
{
}
